apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: bodegas-lab
type: Opaque
stringData:
  DB_SERVER: "Data Source=172.18.34.52;Initial Catalog=PRIVADA;Persist Security Info=True;User ID=administrador;Password=admincentro"
  HEADER_NAME: "Ocp-Apim-Subscription-Key"
  HEADER_VALUE: "5ed08181c2de469e95db2aa5e5129517"